apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-app-deployment
  labels:
    app: ecommerce-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ecommerce-app
  template:
    metadata:
      labels:
        app: ecommerce-app
    spec:
      containers:
      - name: ecommerce-app-container
        image: syedayaseera/e-commerce-app:latest
        ports:
        - containerPort: 8080

