apiVersion: v1
kind: Service
metadata:
  name: ecommerce-app-service
  labels:
    app: ecommerce-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: ecommerce-app

